### PR TITLE
Delete Pygma url

### PR DESCRIPTION
**Pull request by engineer-taro**
The URL for Pygma has been changed, so it needs to be updated.

### CODE REVIEW

**Comment by steven2358** [comment]
The web site you linked says "Pygma is a LatAm based accelerator for early-stage founders". And pygma.app is dead. Any idea were the real Pygma is?

**Comment by engineer-taro** [comment]
Oh, sorry.
I checked and it seems that Pygma is already out of service; there have been no updates since about 2021, and the [official Twitter](https://twitter.com/pygma_app/with_replies) feed has stopped.
I will change the modification to delete the entire Pygma description.

**Comment by steven2358** [comment]
Ok. Anyway, for projects that stop being active we have the file ARCHIVE.md. Could you add it to that list, and use the link of their Twitter? That way we have an archive, and the link is still kind of valid.

**Comment by steven2358** [comment]
Actually, I could do that last step myself, so I just did that. [33d642e](https://github.com/steven2358/awesome-generative-ai/commit/33d642e11314198bbd464348d7925d4ce9511b0d)

**Comment by engineer-taro** [comment]
Thank you for your response!
I have checked the contents.

**Pull request merged**
