### PR TITLE
Adding Loopin AI Meeting Assistant

### PR DESCRIPTION
**Pull request by bhagawatDongre**

### CODE REVIEW

**Comment by steven2358** [comment]
Is there any evidence Loopin is using Generative AI?

**Comment by AmeyLimaye123** [comment]
> Is there any evidence Loopin is using Generative AI?

Hi Steven, Loopin uses OpenAI APIs to generate automated summaries from Meeting transcripts using gpt-3.5 turbo, these transcripts are also generated using OpenAI's Whisper model.

**Comment by steven2358** [comment]
> > Is there any evidence Loopin is using Generative AI?
> 
> Hi Steven, Loopin uses OpenAI APIs to generate automated summaries from Meeting transcripts using gpt-3.5 turbo, these transcripts are also generated using OpenAI's Whisper model.

Sounds good

**Comment by AmeyLimaye123** [comment]
Awesome,
Thanks Steven 🙌

**Pull request merged**
